### ISSUE TITLE
JHotDraw doesn't work

### ISSUE THREAD

**Issue by christianmsc** [qxo/eclipse-metrics-plugin#2]
I've tried to run the metrics plug-in on the JHotDraw project from two different sources:

http://aserg.labsoft.dcc.ufmg.br/jmove2/files/dataset/jhotdraw/JHotDraw%207.6%20original.rar
https://github.com/wumpz/jhotdraw

In both sources, I didn't succeed in calculating the metrics. The plug-in behaves as if I had not enabled the "Enable Metrics" option, which is enabled.

**Comment by rterrabh** [comment]
Hi. I've just tried here and I got the same problem. I enable the "Enable Metrics" option but the plug-in does not calculate any of the metrics.
